// This code contains NVIDIA Confidential Information and is disclosed to you
// under a form of NVIDIA software license agreement provided separately to you.
//
// Notice
// NVIDIA Corporation and its licensors retain all intellectual property and
// proprietary rights in and to this software and related documentation and
// any modifications thereto. Any use, reproduction, disclosure, or
// distribution of this software and related documentation without an express
// license agreement from NVIDIA Corporation is strictly prohibited.
//
// ALL NVIDIA DESIGN SPECIFICATIONS, CODE ARE PROVIDED "AS IS.". NVIDIA MAKES
// NO WARRANTIES, EXPRESSED, IMPLIED, STATUTORY, OR OTHERWISE WITH RESPECT TO
// THE MATERIALS, AND EXPRESSLY DISCLAIMS ALL IMPLIED WARRANTIES OF NONINFRINGEMENT,
// MERCHANTABILITY, AND FITNESS FOR A PARTICULAR PURPOSE.
//
// Information and code furnished is believed to be accurate and reliable.
// However, NVIDIA Corporation assumes no responsibility for the consequences of use of such
// information or for any infringement of patents or other rights of third parties that may
// result from its use. No license is granted by implication or otherwise under any patent
// or patent rights of NVIDIA Corporation. Details are subject to change without notice.
// This code supersedes and replaces all information previously supplied.
// NVIDIA Corporation products are not authorized for use as critical
// components in life support devices or systems without express written approval of
// NVIDIA Corporation.
//
// Copyright (c) 2008-2015 NVIDIA Corporation. All rights reserved.

// This file was generated by NvParameterized/scripts/GenParameterized.pl


#ifndef HEADER_TurbulenceFSAssetParams_0p8_h
#define HEADER_TurbulenceFSAssetParams_0p8_h

#include "NvParametersTypes.h"

#ifndef NV_PARAMETERIZED_ONLY_LAYOUTS
#include "nvparameterized/NvParameterized.h"
#include "nvparameterized/NvParameterizedTraits.h"
#include "NvParameters.h"
#include "NvTraitsInternal.h"
#endif

namespace nvidia
{
namespace parameterized
{

#if PX_VC
#pragma warning(push)
#pragma warning(disable: 4324) // structure was padded due to __declspec(align())
#endif

namespace TurbulenceFSAssetParams_0p8NS
{

struct rangeStructF32_Type;
struct turbulenceRangeStructEnum_Type;
struct LODWeights_Type;
struct HeatParams_Type;
struct DensityParams_Type;
struct NoiseParams_Type;

struct turbulenceRangeStructEnum_Type
{
	const char* min;
	const char* max;
};
struct LODWeights_Type
{
	float maxDistance;
	float distanceWeight;
	float bias;
	float benefitBias;
	float benefitWeight;
};
struct rangeStructF32_Type
{
	float min;
	float max;
};
struct DensityParams_Type
{
	float diffusionCoef;
	float densityFieldFade;
	uint32_t densityGridMultiplier;
};
struct NoiseParams_Type
{
	float noiseStrength;
	physx::PxVec3 noiseSpacePeriod;
	float noiseTimePeriod;
	uint32_t noiseOctaves;
};
struct HeatParams_Type
{
	float temperatureBasedForceMultiplier;
	float ambientTemperature;
	physx::PxVec3 heatForceDirection;
	float thermalConductivity;
};

struct ParametersStruct
{

	turbulenceRangeStructEnum_Type gridXRange;
	turbulenceRangeStructEnum_Type gridYRange;
	turbulenceRangeStructEnum_Type gridZRange;
	physx::PxVec3 gridSizeWorld;
	rangeStructF32_Type updatesPerFrameRange;
	float fluidVelocityMultiplier;
	float fluidVelocityClamp;
	float angularVelocityMultiplier;
	float angularVelocityClamp;
	float linearVelocityMultiplier;
	float linearVelocityClamp;
	float velocityFieldFade;
	float boundaryFadePercentage;
	float boundarySizePercentage;
	NvParameterized::DummyStringStruct collisionFilterDataName;
	NvParameterized::DummyStringStruct fieldBoundaryFilterDataName;
	NvParameterized::DummyStringStruct fieldSamplerFilterDataName;
	uint32_t maxCollidingObjects;
	uint32_t maxHeatSources;
	uint32_t maxSubstanceSources;
	float dragCoeff;
	physx::PxVec3 externalVelocity;
	float fieldVelocityMultiplier;
	float fieldVelocityWeight;
	bool useHeat;
	HeatParams_Type heatParams;
	bool useDensity;
	DensityParams_Type densityParams;
	bool isEnabledOptimizedLOD;
	float customLOD;
	LODWeights_Type lodWeights;
	NoiseParams_Type noiseParams;
	float dragCoeffForRigidBody;
	float fluidViscosity;
	NvParameterized::Interface* volumeRenderMaterialName;

};

static const uint32_t checksum[] = { 0x214fb587, 0x6d0d423a, 0xe826939d, 0x5fb5739c, };

} // namespace TurbulenceFSAssetParams_0p8NS

#ifndef NV_PARAMETERIZED_ONLY_LAYOUTS
class TurbulenceFSAssetParams_0p8 : public NvParameterized::NvParameters, public TurbulenceFSAssetParams_0p8NS::ParametersStruct
{
public:
	TurbulenceFSAssetParams_0p8(NvParameterized::Traits* traits, void* buf = 0, int32_t* refCount = 0);

	virtual ~TurbulenceFSAssetParams_0p8();

	virtual void destroy();

	static const char* staticClassName(void)
	{
		return("TurbulenceFSAssetParams");
	}

	const char* className(void) const
	{
		return(staticClassName());
	}

	static const uint32_t ClassVersion = ((uint32_t)0 << 16) + (uint32_t)8;

	static uint32_t staticVersion(void)
	{
		return ClassVersion;
	}

	uint32_t version(void) const
	{
		return(staticVersion());
	}

	static const uint32_t ClassAlignment = 8;

	static const uint32_t* staticChecksum(uint32_t& bits)
	{
		bits = 8 * sizeof(TurbulenceFSAssetParams_0p8NS::checksum);
		return TurbulenceFSAssetParams_0p8NS::checksum;
	}

	static void freeParameterDefinitionTable(NvParameterized::Traits* traits);

	const uint32_t* checksum(uint32_t& bits) const
	{
		return staticChecksum(bits);
	}

	const TurbulenceFSAssetParams_0p8NS::ParametersStruct& parameters(void) const
	{
		TurbulenceFSAssetParams_0p8* tmpThis = const_cast<TurbulenceFSAssetParams_0p8*>(this);
		return *(static_cast<TurbulenceFSAssetParams_0p8NS::ParametersStruct*>(tmpThis));
	}

	TurbulenceFSAssetParams_0p8NS::ParametersStruct& parameters(void)
	{
		return *(static_cast<TurbulenceFSAssetParams_0p8NS::ParametersStruct*>(this));
	}

	virtual NvParameterized::ErrorType getParameterHandle(const char* long_name, NvParameterized::Handle& handle) const;
	virtual NvParameterized::ErrorType getParameterHandle(const char* long_name, NvParameterized::Handle& handle);

	void initDefaults(void);

protected:

	virtual const NvParameterized::DefinitionImpl* getParameterDefinitionTree(void);
	virtual const NvParameterized::DefinitionImpl* getParameterDefinitionTree(void) const;


	virtual void getVarPtr(const NvParameterized::Handle& handle, void*& ptr, size_t& offset) const;

private:

	void buildTree(void);
	void initDynamicArrays(void);
	void initStrings(void);
	void initReferences(void);
	void freeDynamicArrays(void);
	void freeStrings(void);
	void freeReferences(void);

	static bool mBuiltFlag;
	static NvParameterized::MutexType mBuiltFlagMutex;
};

class TurbulenceFSAssetParams_0p8Factory : public NvParameterized::Factory
{
	static const char* const vptr;

public:

	virtual void freeParameterDefinitionTable(NvParameterized::Traits* traits)
	{
		TurbulenceFSAssetParams_0p8::freeParameterDefinitionTable(traits);
	}

	virtual NvParameterized::Interface* create(NvParameterized::Traits* paramTraits)
	{
		// placement new on this class using mParameterizedTraits

		void* newPtr = paramTraits->alloc(sizeof(TurbulenceFSAssetParams_0p8), TurbulenceFSAssetParams_0p8::ClassAlignment);
		if (!NvParameterized::IsAligned(newPtr, TurbulenceFSAssetParams_0p8::ClassAlignment))
		{
			NV_PARAM_TRAITS_WARNING(paramTraits, "Unaligned memory allocation for class TurbulenceFSAssetParams_0p8");
			paramTraits->free(newPtr);
			return 0;
		}

		memset(newPtr, 0, sizeof(TurbulenceFSAssetParams_0p8)); // always initialize memory allocated to zero for default values
		return NV_PARAM_PLACEMENT_NEW(newPtr, TurbulenceFSAssetParams_0p8)(paramTraits);
	}

	virtual NvParameterized::Interface* finish(NvParameterized::Traits* paramTraits, void* bufObj, void* bufStart, int32_t* refCount)
	{
		if (!NvParameterized::IsAligned(bufObj, TurbulenceFSAssetParams_0p8::ClassAlignment)
		        || !NvParameterized::IsAligned(bufStart, TurbulenceFSAssetParams_0p8::ClassAlignment))
		{
			NV_PARAM_TRAITS_WARNING(paramTraits, "Unaligned memory allocation for class TurbulenceFSAssetParams_0p8");
			return 0;
		}

		// Init NvParameters-part
		// We used to call empty constructor of TurbulenceFSAssetParams_0p8 here
		// but it may call default constructors of members and spoil the data
		NV_PARAM_PLACEMENT_NEW(bufObj, NvParameterized::NvParameters)(paramTraits, bufStart, refCount);

		// Init vtable (everything else is already initialized)
		*(const char**)bufObj = vptr;

		return (TurbulenceFSAssetParams_0p8*)bufObj;
	}

	virtual const char* getClassName()
	{
		return (TurbulenceFSAssetParams_0p8::staticClassName());
	}

	virtual uint32_t getVersion()
	{
		return (TurbulenceFSAssetParams_0p8::staticVersion());
	}

	virtual uint32_t getAlignment()
	{
		return (TurbulenceFSAssetParams_0p8::ClassAlignment);
	}

	virtual const uint32_t* getChecksum(uint32_t& bits)
	{
		return (TurbulenceFSAssetParams_0p8::staticChecksum(bits));
	}
};
#endif // NV_PARAMETERIZED_ONLY_LAYOUTS

} // namespace parameterized
} // namespace nvidia

#if PX_VC
#pragma warning(pop)
#endif

#endif
