// This code contains NVIDIA Confidential Information and is disclosed to you
// under a form of NVIDIA software license agreement provided separately to you.
//
// Notice
// NVIDIA Corporation and its licensors retain all intellectual property and
// proprietary rights in and to this software and related documentation and
// any modifications thereto. Any use, reproduction, disclosure, or
// distribution of this software and related documentation without an express
// license agreement from NVIDIA Corporation is strictly prohibited.
//
// ALL NVIDIA DESIGN SPECIFICATIONS, CODE ARE PROVIDED "AS IS.". NVIDIA MAKES
// NO WARRANTIES, EXPRESSED, IMPLIED, STATUTORY, OR OTHERWISE WITH RESPECT TO
// THE MATERIALS, AND EXPRESSLY DISCLAIMS ALL IMPLIED WARRANTIES OF NONINFRINGEMENT,
// MERCHANTABILITY, AND FITNESS FOR A PARTICULAR PURPOSE.
//
// Information and code furnished is believed to be accurate and reliable.
// However, NVIDIA Corporation assumes no responsibility for the consequences of use of such
// information or for any infringement of patents or other rights of third parties that may
// result from its use. No license is granted by implication or otherwise under any patent
// or patent rights of NVIDIA Corporation. Details are subject to change without notice.
// This code supersedes and replaces all information previously supplied.
// NVIDIA Corporation products are not authorized for use as critical
// components in life support devices or systems without express written approval of
// NVIDIA Corporation.
//
// Copyright (c) 2008-2015 NVIDIA Corporation. All rights reserved.

// This file was generated by NvParameterized/scripts/GenParameterized.pl


#ifndef HEADER_TurbulenceFSAssetParams_1p5_h
#define HEADER_TurbulenceFSAssetParams_1p5_h

#include "NvParametersTypes.h"

#ifndef NV_PARAMETERIZED_ONLY_LAYOUTS
#include "nvparameterized/NvParameterized.h"
#include "nvparameterized/NvParameterizedTraits.h"
#include "NvParameters.h"
#include "NvTraitsInternal.h"
#endif

namespace nvidia
{
namespace parameterized
{

#if PX_VC
#pragma warning(push)
#pragma warning(disable: 4324) // structure was padded due to __declspec(align())
#endif

namespace TurbulenceFSAssetParams_1p5NS
{

struct HeatParams_Type;
struct DensityParams_Type;
struct NoiseParams_Type;
struct FlameParams_Type;

struct FlameParams_Type
{
	float IgnitionTemp;
	float MaxIgnitionTemp;
	float ReactionSpeed;
	float HeatReleased;
	float DensityEmission;
	float FuelInefficiency;
	float Expansion;
	float Cooling;
	float Buoyancy;
	physx::PxVec3 BuoyancyUpVector;
	float RoomTemperature;
	physx::PxVec4 Dissipation;
	uint32_t ResolutionMultiplier;
};
struct DensityParams_Type
{
	float diffusionCoef;
	float densityFieldFade;
	uint32_t densityGridMultiplier;
};
struct NoiseParams_Type
{
	float noiseStrength;
	physx::PxVec3 noiseSpacePeriod;
	float noiseTimePeriod;
	uint32_t noiseOctaves;
};
struct HeatParams_Type
{
	float temperatureBasedForceMultiplier;
	float ambientTemperature;
	physx::PxVec3 heatForceDirection;
	float thermalConductivity;
};

struct ParametersStruct
{

	const char* gridXSize;
	const char* gridYSize;
	const char* gridZSize;
	physx::PxVec3 gridSizeWorld;
	float updatesPerFrame;
	float angularVelocityMultiplier;
	float angularVelocityClamp;
	float linearVelocityMultiplier;
	float linearVelocityClamp;
	float velocityFieldFadeTime;
	float velocityFieldFadeDelay;
	float velocityFieldFadeIntensity;
	float boundaryFadePercentage;
	float boundarySizePercentage;
	NvParameterized::DummyStringStruct collisionFilterDataName;
	NvParameterized::DummyStringStruct fieldBoundaryFilterDataName;
	NvParameterized::DummyStringStruct fieldSamplerFilterDataName;
	uint32_t maxCollidingObjects;
	uint32_t maxVelocitySources;
	uint32_t maxHeatSources;
	uint32_t maxSubstanceSources;
	float dragCoeff;
	physx::PxVec3 externalVelocity;
	float fieldVelocityMultiplier;
	float fieldVelocityWeight;
	bool useHeat;
	HeatParams_Type heatParams;
	bool useDensity;
	DensityParams_Type densityParams;
	bool isEnabledOptimizedLOD;
	NoiseParams_Type noiseParams;
	float dragCoeffForRigidBody;
	float fluidViscosity;
	NvParameterized::Interface* volumeRenderMaterialName;
	bool useFlame;
	FlameParams_Type flameParams;
	const char* solverAccuracy;

};

static const uint32_t checksum[] = { 0x2d35c303, 0x064cbc83, 0x89526ff1, 0x53f1d740, };

} // namespace TurbulenceFSAssetParams_1p5NS

#ifndef NV_PARAMETERIZED_ONLY_LAYOUTS
class TurbulenceFSAssetParams_1p5 : public NvParameterized::NvParameters, public TurbulenceFSAssetParams_1p5NS::ParametersStruct
{
public:
	TurbulenceFSAssetParams_1p5(NvParameterized::Traits* traits, void* buf = 0, int32_t* refCount = 0);

	virtual ~TurbulenceFSAssetParams_1p5();

	virtual void destroy();

	static const char* staticClassName(void)
	{
		return("TurbulenceFSAssetParams");
	}

	const char* className(void) const
	{
		return(staticClassName());
	}

	static const uint32_t ClassVersion = ((uint32_t)1 << 16) + (uint32_t)5;

	static uint32_t staticVersion(void)
	{
		return ClassVersion;
	}

	uint32_t version(void) const
	{
		return(staticVersion());
	}

	static const uint32_t ClassAlignment = 8;

	static const uint32_t* staticChecksum(uint32_t& bits)
	{
		bits = 8 * sizeof(TurbulenceFSAssetParams_1p5NS::checksum);
		return TurbulenceFSAssetParams_1p5NS::checksum;
	}

	static void freeParameterDefinitionTable(NvParameterized::Traits* traits);

	const uint32_t* checksum(uint32_t& bits) const
	{
		return staticChecksum(bits);
	}

	const TurbulenceFSAssetParams_1p5NS::ParametersStruct& parameters(void) const
	{
		TurbulenceFSAssetParams_1p5* tmpThis = const_cast<TurbulenceFSAssetParams_1p5*>(this);
		return *(static_cast<TurbulenceFSAssetParams_1p5NS::ParametersStruct*>(tmpThis));
	}

	TurbulenceFSAssetParams_1p5NS::ParametersStruct& parameters(void)
	{
		return *(static_cast<TurbulenceFSAssetParams_1p5NS::ParametersStruct*>(this));
	}

	virtual NvParameterized::ErrorType getParameterHandle(const char* long_name, NvParameterized::Handle& handle) const;
	virtual NvParameterized::ErrorType getParameterHandle(const char* long_name, NvParameterized::Handle& handle);

	void initDefaults(void);

protected:

	virtual const NvParameterized::DefinitionImpl* getParameterDefinitionTree(void);
	virtual const NvParameterized::DefinitionImpl* getParameterDefinitionTree(void) const;


	virtual void getVarPtr(const NvParameterized::Handle& handle, void*& ptr, size_t& offset) const;

private:

	void buildTree(void);
	void initDynamicArrays(void);
	void initStrings(void);
	void initReferences(void);
	void freeDynamicArrays(void);
	void freeStrings(void);
	void freeReferences(void);

	static bool mBuiltFlag;
	static NvParameterized::MutexType mBuiltFlagMutex;
};

class TurbulenceFSAssetParams_1p5Factory : public NvParameterized::Factory
{
	static const char* const vptr;

public:

	virtual void freeParameterDefinitionTable(NvParameterized::Traits* traits)
	{
		TurbulenceFSAssetParams_1p5::freeParameterDefinitionTable(traits);
	}

	virtual NvParameterized::Interface* create(NvParameterized::Traits* paramTraits)
	{
		// placement new on this class using mParameterizedTraits

		void* newPtr = paramTraits->alloc(sizeof(TurbulenceFSAssetParams_1p5), TurbulenceFSAssetParams_1p5::ClassAlignment);
		if (!NvParameterized::IsAligned(newPtr, TurbulenceFSAssetParams_1p5::ClassAlignment))
		{
			NV_PARAM_TRAITS_WARNING(paramTraits, "Unaligned memory allocation for class TurbulenceFSAssetParams_1p5");
			paramTraits->free(newPtr);
			return 0;
		}

		memset(newPtr, 0, sizeof(TurbulenceFSAssetParams_1p5)); // always initialize memory allocated to zero for default values
		return NV_PARAM_PLACEMENT_NEW(newPtr, TurbulenceFSAssetParams_1p5)(paramTraits);
	}

	virtual NvParameterized::Interface* finish(NvParameterized::Traits* paramTraits, void* bufObj, void* bufStart, int32_t* refCount)
	{
		if (!NvParameterized::IsAligned(bufObj, TurbulenceFSAssetParams_1p5::ClassAlignment)
		        || !NvParameterized::IsAligned(bufStart, TurbulenceFSAssetParams_1p5::ClassAlignment))
		{
			NV_PARAM_TRAITS_WARNING(paramTraits, "Unaligned memory allocation for class TurbulenceFSAssetParams_1p5");
			return 0;
		}

		// Init NvParameters-part
		// We used to call empty constructor of TurbulenceFSAssetParams_1p5 here
		// but it may call default constructors of members and spoil the data
		NV_PARAM_PLACEMENT_NEW(bufObj, NvParameterized::NvParameters)(paramTraits, bufStart, refCount);

		// Init vtable (everything else is already initialized)
		*(const char**)bufObj = vptr;

		return (TurbulenceFSAssetParams_1p5*)bufObj;
	}

	virtual const char* getClassName()
	{
		return (TurbulenceFSAssetParams_1p5::staticClassName());
	}

	virtual uint32_t getVersion()
	{
		return (TurbulenceFSAssetParams_1p5::staticVersion());
	}

	virtual uint32_t getAlignment()
	{
		return (TurbulenceFSAssetParams_1p5::ClassAlignment);
	}

	virtual const uint32_t* getChecksum(uint32_t& bits)
	{
		return (TurbulenceFSAssetParams_1p5::staticChecksum(bits));
	}
};
#endif // NV_PARAMETERIZED_ONLY_LAYOUTS

} // namespace parameterized
} // namespace nvidia

#if PX_VC
#pragma warning(pop)
#endif

#endif
