// This code contains NVIDIA Confidential Information and is disclosed to you
// under a form of NVIDIA software license agreement provided separately to you.
//
// Notice
// NVIDIA Corporation and its licensors retain all intellectual property and
// proprietary rights in and to this software and related documentation and
// any modifications thereto. Any use, reproduction, disclosure, or
// distribution of this software and related documentation without an express
// license agreement from NVIDIA Corporation is strictly prohibited.
//
// ALL NVIDIA DESIGN SPECIFICATIONS, CODE ARE PROVIDED "AS IS.". NVIDIA MAKES
// NO WARRANTIES, EXPRESSED, IMPLIED, STATUTORY, OR OTHERWISE WITH RESPECT TO
// THE MATERIALS, AND EXPRESSLY DISCLAIMS ALL IMPLIED WARRANTIES OF NONINFRINGEMENT,
// MERCHANTABILITY, AND FITNESS FOR A PARTICULAR PURPOSE.
//
// Information and code furnished is believed to be accurate and reliable.
// However, NVIDIA Corporation assumes no responsibility for the consequences of use of such
// information or for any infringement of patents or other rights of third parties that may
// result from its use. No license is granted by implication or otherwise under any patent
// or patent rights of NVIDIA Corporation. Details are subject to change without notice.
// This code supersedes and replaces all information previously supplied.
// NVIDIA Corporation products are not authorized for use as critical
// components in life support devices or systems without express written approval of
// NVIDIA Corporation.
//
// Copyright (c) 2008-2015 NVIDIA Corporation. All rights reserved.

// This file was generated by NvParameterized/scripts/GenParameterized.pl


#ifndef HEADER_EffectPackageAssetParams_h
#define HEADER_EffectPackageAssetParams_h

#include "NvParametersTypes.h"

#ifndef NV_PARAMETERIZED_ONLY_LAYOUTS
#include "nvparameterized/NvParameterized.h"
#include "nvparameterized/NvParameterizedTraits.h"
#include "NvParameters.h"
#include "NvTraitsInternal.h"
#endif

namespace nvidia
{
namespace particles
{

#if PX_VC
#pragma warning(push)
#pragma warning(disable: 4324) // structure was padded due to __declspec(align())
#endif

namespace EffectPackageAssetParamsNS
{

struct ControlPoint_Type;
struct EffectPath_Type;
struct LevelOfDetailSettings_Type;

struct TRANSFORM_DynamicArray1D_Type
{
	physx::PxTransform* buf;
	bool isAllocated;
	int32_t elementSize;
	int32_t arraySizes[1];
};

struct ControlPoint_DynamicArray1D_Type
{
	ControlPoint_Type* buf;
	bool isAllocated;
	int32_t elementSize;
	int32_t arraySizes[1];
};

struct REF_DynamicArray1D_Type
{
	NvParameterized::Interface** buf;
	bool isAllocated;
	int32_t elementSize;
	int32_t arraySizes[1];
};

struct ControlPoint_Type
{
	float x;
	float y;
};
struct LevelOfDetailSettings_Type
{
	bool UniqueRenderVolume;
	float FadeDistanceBegin;
	float FadeDistanceEnd;
	bool RandomizeEmitterRate;
	float FadeOutRate;
	bool CullByDistance;
	bool CullOffScreen;
	float OffScreenCullTime;
	float NonVisibleDeleteTime;
	float ScreenCullSize;
	float ScreenCullDistance;
	bool FadeEmitterRate;
	bool FadeAttractorFieldStrength;
	bool FadeJetFieldStrength;
	bool FadeTurbulenceVelocity;
	bool FadeTurbulenceNoise;
	bool FadeTurbulenceExternalVelocity;
	bool FadeTurbulenceVelocityWeight;
	bool FadeHeatSourceTemperature;
	bool FadeForceFieldStrength;
	bool FadeForceFieldScale;
};
struct EffectPath_Type
{
	const char* PlaybackMode;
	float PathDuration;
	uint32_t LoopIndex;
	TRANSFORM_DynamicArray1D_Type ControlPoints;
	ControlPoint_DynamicArray1D_Type Scale;
	ControlPoint_DynamicArray1D_Type Speed;
};

struct ParametersStruct
{

	LevelOfDetailSettings_Type LODSettings;
	EffectPath_Type Path;
	REF_DynamicArray1D_Type Effects;
	NvParameterized::DummyStringStruct toolString;

};

static const uint32_t checksum[] = { 0xdfc6da4d, 0xdcc561ad, 0x411cf278, 0x3bdc08bc, };

} // namespace EffectPackageAssetParamsNS

#ifndef NV_PARAMETERIZED_ONLY_LAYOUTS
class EffectPackageAssetParams : public NvParameterized::NvParameters, public EffectPackageAssetParamsNS::ParametersStruct
{
public:
	EffectPackageAssetParams(NvParameterized::Traits* traits, void* buf = 0, int32_t* refCount = 0);

	virtual ~EffectPackageAssetParams();

	virtual void destroy();

	static const char* staticClassName(void)
	{
		return("EffectPackageAssetParams");
	}

	const char* className(void) const
	{
		return(staticClassName());
	}

	static const uint32_t ClassVersion = ((uint32_t)0 << 16) + (uint32_t)1;

	static uint32_t staticVersion(void)
	{
		return ClassVersion;
	}

	uint32_t version(void) const
	{
		return(staticVersion());
	}

	static const uint32_t ClassAlignment = 8;

	static const uint32_t* staticChecksum(uint32_t& bits)
	{
		bits = 8 * sizeof(EffectPackageAssetParamsNS::checksum);
		return EffectPackageAssetParamsNS::checksum;
	}

	static void freeParameterDefinitionTable(NvParameterized::Traits* traits);

	const uint32_t* checksum(uint32_t& bits) const
	{
		return staticChecksum(bits);
	}

	const EffectPackageAssetParamsNS::ParametersStruct& parameters(void) const
	{
		EffectPackageAssetParams* tmpThis = const_cast<EffectPackageAssetParams*>(this);
		return *(static_cast<EffectPackageAssetParamsNS::ParametersStruct*>(tmpThis));
	}

	EffectPackageAssetParamsNS::ParametersStruct& parameters(void)
	{
		return *(static_cast<EffectPackageAssetParamsNS::ParametersStruct*>(this));
	}

	virtual NvParameterized::ErrorType getParameterHandle(const char* long_name, NvParameterized::Handle& handle) const;
	virtual NvParameterized::ErrorType getParameterHandle(const char* long_name, NvParameterized::Handle& handle);

	void initDefaults(void);

protected:

	virtual const NvParameterized::DefinitionImpl* getParameterDefinitionTree(void);
	virtual const NvParameterized::DefinitionImpl* getParameterDefinitionTree(void) const;


	virtual void getVarPtr(const NvParameterized::Handle& handle, void*& ptr, size_t& offset) const;

private:

	void buildTree(void);
	void initDynamicArrays(void);
	void initStrings(void);
	void initReferences(void);
	void freeDynamicArrays(void);
	void freeStrings(void);
	void freeReferences(void);

	static bool mBuiltFlag;
	static NvParameterized::MutexType mBuiltFlagMutex;
};

class EffectPackageAssetParamsFactory : public NvParameterized::Factory
{
	static const char* const vptr;

public:

	virtual void freeParameterDefinitionTable(NvParameterized::Traits* traits)
	{
		EffectPackageAssetParams::freeParameterDefinitionTable(traits);
	}

	virtual NvParameterized::Interface* create(NvParameterized::Traits* paramTraits)
	{
		// placement new on this class using mParameterizedTraits

		void* newPtr = paramTraits->alloc(sizeof(EffectPackageAssetParams), EffectPackageAssetParams::ClassAlignment);
		if (!NvParameterized::IsAligned(newPtr, EffectPackageAssetParams::ClassAlignment))
		{
			NV_PARAM_TRAITS_WARNING(paramTraits, "Unaligned memory allocation for class EffectPackageAssetParams");
			paramTraits->free(newPtr);
			return 0;
		}

		memset(newPtr, 0, sizeof(EffectPackageAssetParams)); // always initialize memory allocated to zero for default values
		return NV_PARAM_PLACEMENT_NEW(newPtr, EffectPackageAssetParams)(paramTraits);
	}

	virtual NvParameterized::Interface* finish(NvParameterized::Traits* paramTraits, void* bufObj, void* bufStart, int32_t* refCount)
	{
		if (!NvParameterized::IsAligned(bufObj, EffectPackageAssetParams::ClassAlignment)
		        || !NvParameterized::IsAligned(bufStart, EffectPackageAssetParams::ClassAlignment))
		{
			NV_PARAM_TRAITS_WARNING(paramTraits, "Unaligned memory allocation for class EffectPackageAssetParams");
			return 0;
		}

		// Init NvParameters-part
		// We used to call empty constructor of EffectPackageAssetParams here
		// but it may call default constructors of members and spoil the data
		NV_PARAM_PLACEMENT_NEW(bufObj, NvParameterized::NvParameters)(paramTraits, bufStart, refCount);

		// Init vtable (everything else is already initialized)
		*(const char**)bufObj = vptr;

		return (EffectPackageAssetParams*)bufObj;
	}

	virtual const char* getClassName()
	{
		return (EffectPackageAssetParams::staticClassName());
	}

	virtual uint32_t getVersion()
	{
		return (EffectPackageAssetParams::staticVersion());
	}

	virtual uint32_t getAlignment()
	{
		return (EffectPackageAssetParams::ClassAlignment);
	}

	virtual const uint32_t* getChecksum(uint32_t& bits)
	{
		return (EffectPackageAssetParams::staticChecksum(bits));
	}
};
#endif // NV_PARAMETERIZED_ONLY_LAYOUTS

} // namespace particles
} // namespace nvidia

#if PX_VC
#pragma warning(pop)
#endif

#endif
