// This code contains NVIDIA Confidential Information and is disclosed to you
// under a form of NVIDIA software license agreement provided separately to you.
//
// Notice
// NVIDIA Corporation and its licensors retain all intellectual property and
// proprietary rights in and to this software and related documentation and
// any modifications thereto. Any use, reproduction, disclosure, or
// distribution of this software and related documentation without an express
// license agreement from NVIDIA Corporation is strictly prohibited.
//
// ALL NVIDIA DESIGN SPECIFICATIONS, CODE ARE PROVIDED "AS IS.". NVIDIA MAKES
// NO WARRANTIES, EXPRESSED, IMPLIED, STATUTORY, OR OTHERWISE WITH RESPECT TO
// THE MATERIALS, AND EXPRESSLY DISCLAIMS ALL IMPLIED WARRANTIES OF NONINFRINGEMENT,
// MERCHANTABILITY, AND FITNESS FOR A PARTICULAR PURPOSE.
//
// Information and code furnished is believed to be accurate and reliable.
// However, NVIDIA Corporation assumes no responsibility for the consequences of use of such
// information or for any infringement of patents or other rights of third parties that may
// result from its use. No license is granted by implication or otherwise under any patent
// or patent rights of NVIDIA Corporation. Details are subject to change without notice.
// This code supersedes and replaces all information previously supplied.
// NVIDIA Corporation products are not authorized for use as critical
// components in life support devices or systems without express written approval of
// NVIDIA Corporation.
//
// Copyright (c) 2008-2015 NVIDIA Corporation. All rights reserved.

// This file was generated by NvParameterized/scripts/GenParameterized.pl


#ifndef HEADER_BasicFSDebugRenderParams_h
#define HEADER_BasicFSDebugRenderParams_h

#include "NvParametersTypes.h"

#ifndef NV_PARAMETERIZED_ONLY_LAYOUTS
#include "nvparameterized/NvParameterized.h"
#include "nvparameterized/NvParameterizedTraits.h"
#include "NvParameters.h"
#include "NvTraitsInternal.h"
#endif

namespace nvidia
{
namespace basicfs
{

#if PX_VC
#pragma warning(push)
#pragma warning(disable: 4324) // structure was padded due to __declspec(align())
#endif

namespace BasicFSDebugRenderParamsNS
{



struct ParametersStruct
{

	bool VISUALIZE_JET_FS_ACTOR;
	bool VISUALIZE_JET_FS_ACTOR_NAME;
	bool VISUALIZE_JET_FS_SHAPE;
	bool VISUALIZE_JET_FS_FIELD;
	bool VISUALIZE_JET_FS_POSE;
	float JET_FS_FIELD_SCALE;
	bool VISUALIZE_ATTRACTOR_FS_ACTOR;
	bool VISUALIZE_ATTRACTOR_FS_ACTOR_NAME;
	bool VISUALIZE_ATTRACTOR_FS_SHAPE;
	bool VISUALIZE_ATTRACTOR_FS_FIELD;
	bool VISUALIZE_ATTRACTOR_FS_POSE;
	bool VISUALIZE_VORTEX_FS_ACTOR;
	bool VISUALIZE_VORTEX_FS_ACTOR_NAME;
	bool VISUALIZE_VORTEX_FS_SHAPE;
	bool VISUALIZE_VORTEX_FS_FIELD;
	bool VISUALIZE_VORTEX_FS_POSE;
	bool VISUALIZE_NOISE_FS_ACTOR;
	bool VISUALIZE_NOISE_FS_ACTOR_NAME;
	bool VISUALIZE_NOISE_FS_SHAPE;
	bool VISUALIZE_NOISE_FS_POSE;
	bool VISUALIZE_WIND_FS_ACTOR;
	bool VISUALIZE_WIND_FS_ACTOR_NAME;

};

static const uint32_t checksum[] = { 0xb0169d27, 0x35d0161d, 0xa6b13602, 0x90135fb1, };

} // namespace BasicFSDebugRenderParamsNS

#ifndef NV_PARAMETERIZED_ONLY_LAYOUTS
class BasicFSDebugRenderParams : public NvParameterized::NvParameters, public BasicFSDebugRenderParamsNS::ParametersStruct
{
public:
	BasicFSDebugRenderParams(NvParameterized::Traits* traits, void* buf = 0, int32_t* refCount = 0);

	virtual ~BasicFSDebugRenderParams();

	virtual void destroy();

	static const char* staticClassName(void)
	{
		return("BasicFSDebugRenderParams");
	}

	const char* className(void) const
	{
		return(staticClassName());
	}

	static const uint32_t ClassVersion = ((uint32_t)0 << 16) + (uint32_t)0;

	static uint32_t staticVersion(void)
	{
		return ClassVersion;
	}

	uint32_t version(void) const
	{
		return(staticVersion());
	}

	static const uint32_t ClassAlignment = 8;

	static const uint32_t* staticChecksum(uint32_t& bits)
	{
		bits = 8 * sizeof(BasicFSDebugRenderParamsNS::checksum);
		return BasicFSDebugRenderParamsNS::checksum;
	}

	static void freeParameterDefinitionTable(NvParameterized::Traits* traits);

	const uint32_t* checksum(uint32_t& bits) const
	{
		return staticChecksum(bits);
	}

	const BasicFSDebugRenderParamsNS::ParametersStruct& parameters(void) const
	{
		BasicFSDebugRenderParams* tmpThis = const_cast<BasicFSDebugRenderParams*>(this);
		return *(static_cast<BasicFSDebugRenderParamsNS::ParametersStruct*>(tmpThis));
	}

	BasicFSDebugRenderParamsNS::ParametersStruct& parameters(void)
	{
		return *(static_cast<BasicFSDebugRenderParamsNS::ParametersStruct*>(this));
	}

	virtual NvParameterized::ErrorType getParameterHandle(const char* long_name, NvParameterized::Handle& handle) const;
	virtual NvParameterized::ErrorType getParameterHandle(const char* long_name, NvParameterized::Handle& handle);

	void initDefaults(void);

protected:

	virtual const NvParameterized::DefinitionImpl* getParameterDefinitionTree(void);
	virtual const NvParameterized::DefinitionImpl* getParameterDefinitionTree(void) const;


	virtual void getVarPtr(const NvParameterized::Handle& handle, void*& ptr, size_t& offset) const;

private:

	void buildTree(void);
	void initDynamicArrays(void);
	void initStrings(void);
	void initReferences(void);
	void freeDynamicArrays(void);
	void freeStrings(void);
	void freeReferences(void);

	static bool mBuiltFlag;
	static NvParameterized::MutexType mBuiltFlagMutex;
};

class BasicFSDebugRenderParamsFactory : public NvParameterized::Factory
{
	static const char* const vptr;

public:

	virtual void freeParameterDefinitionTable(NvParameterized::Traits* traits)
	{
		BasicFSDebugRenderParams::freeParameterDefinitionTable(traits);
	}

	virtual NvParameterized::Interface* create(NvParameterized::Traits* paramTraits)
	{
		// placement new on this class using mParameterizedTraits

		void* newPtr = paramTraits->alloc(sizeof(BasicFSDebugRenderParams), BasicFSDebugRenderParams::ClassAlignment);
		if (!NvParameterized::IsAligned(newPtr, BasicFSDebugRenderParams::ClassAlignment))
		{
			NV_PARAM_TRAITS_WARNING(paramTraits, "Unaligned memory allocation for class BasicFSDebugRenderParams");
			paramTraits->free(newPtr);
			return 0;
		}

		memset(newPtr, 0, sizeof(BasicFSDebugRenderParams)); // always initialize memory allocated to zero for default values
		return NV_PARAM_PLACEMENT_NEW(newPtr, BasicFSDebugRenderParams)(paramTraits);
	}

	virtual NvParameterized::Interface* finish(NvParameterized::Traits* paramTraits, void* bufObj, void* bufStart, int32_t* refCount)
	{
		if (!NvParameterized::IsAligned(bufObj, BasicFSDebugRenderParams::ClassAlignment)
		        || !NvParameterized::IsAligned(bufStart, BasicFSDebugRenderParams::ClassAlignment))
		{
			NV_PARAM_TRAITS_WARNING(paramTraits, "Unaligned memory allocation for class BasicFSDebugRenderParams");
			return 0;
		}

		// Init NvParameters-part
		// We used to call empty constructor of BasicFSDebugRenderParams here
		// but it may call default constructors of members and spoil the data
		NV_PARAM_PLACEMENT_NEW(bufObj, NvParameterized::NvParameters)(paramTraits, bufStart, refCount);

		// Init vtable (everything else is already initialized)
		*(const char**)bufObj = vptr;

		return (BasicFSDebugRenderParams*)bufObj;
	}

	virtual const char* getClassName()
	{
		return (BasicFSDebugRenderParams::staticClassName());
	}

	virtual uint32_t getVersion()
	{
		return (BasicFSDebugRenderParams::staticVersion());
	}

	virtual uint32_t getAlignment()
	{
		return (BasicFSDebugRenderParams::ClassAlignment);
	}

	virtual const uint32_t* getChecksum(uint32_t& bits)
	{
		return (BasicFSDebugRenderParams::staticChecksum(bits));
	}
};
#endif // NV_PARAMETERIZED_ONLY_LAYOUTS

} // namespace basicfs
} // namespace nvidia

#if PX_VC
#pragma warning(pop)
#endif

#endif
